// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2e2xmW4ja766FpdT_Si8GnlTdQPNoeLM',
    appId: '1:387692813225:android:50a9b5a028b355288fc2b8',
    messagingSenderId: '387692813225',
    projectId: 'vr-calendar-871f2',
    storageBucket: 'vr-calendar-871f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBumThgVjPHkdIa-_fYtWRdn30BlLZSSmo',
    appId: '1:387692813225:ios:57f0b6420456dc5e8fc2b8',
    messagingSenderId: '387692813225',
    projectId: 'vr-calendar-871f2',
    storageBucket: 'vr-calendar-871f2.appspot.com',
    androidClientId: '387692813225-bt6de60ov8bivfuo2fjbjn7hmi5ch7ip.apps.googleusercontent.com',
    iosClientId: '387692813225-7hgoc106pquuh4t3o0jke4q75ipkef5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.vrProject',
  );
}
